export const MESSAGES = {
  success: "success!",
  register: "Signed Up successfully!",
  login: "Logged in successfully!",
  update: "Updated!",
  delete: "Deleted!",
  productCreated: "Product Created",
  productOutStock: "Product out of stock!",
  addProduct: "Product Added",
  decreasedProduct: "Product Decreased",
  addComment: "Your comment has send!",
  deleteProduct: "Product Deleted",
  taskCreated: "Task Created",
  taskUpdated: "Task Updated",
  taskDeleted: "Task Deleted",
  taskEdited: "Task Edited",
  blogCreated: "Blog Created",
  blogUpdated: "Blog Updated",
  blogDeleted: "Blog Deleted",
  blogEdited: "Blog Edited",
  invalidId: "Invalid Id",
  noContent: "There is no data!",
  productEdited: "Product Edited",
  badRequest: "Bad Request!",
  unAuthorized: "You are not authorized!",
  user_exist: "Username already Exists!",
  usernameEmpty: "Username cannot be empty!",
  errorOccurred: "An error occurred!",
  errorUpdateProfile: "An error occurred while updating the profile.",
  userNotFound: "Username or password is In-Correct!",
  productNotFound: "Product not found!",
  noMatchPassword: "Current Password is in-correct!",
  confirmPass: "The password is not the same.",
  forbidden: "Access Denied!",
  fillInp: "Please enter valid Data!",
  fields: "Please fill all fields!",
  image: "Please put image!",
  updateProfile: "Profile Updated",
  updateRole: "User Role Updated!",
  deleteAdmin: "User Deleted!",
  adminHasContent: "Admin has content!",
  wentWrong: "Something went wrong!",
  failed: "failed!",
  server: "Server Error!",
};

export const STATUS_CODES = {
  success: 200,
  created: 201,
  updated: 202,
  badRequest: 400,
  unAuthorized: 401,
  forbidden: 403,
  exist: 422,
  not_found: 404,
  server: 500,
};
